# Generated by Django 4.2 on 2024-11-09 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchase', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchase',
            name='status',
            field=models.SmallIntegerField(choices=[(10, 'paid'), (-10, 'Not paid')], default=-10),
        ),
    ]
