# Generated by Django 4.2 on 2024-11-09 16:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0002_alter_gateway_gateway_code'),
        ('purchase', '0002_purchase_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchase',
            name='payment',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='purchases', to='finance.payment'),
        ),
    ]
