# Generated by Django 4.2 on 2024-11-07 21:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('package', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='package',
            name='is_enable',
            field=models.BooleanField(default=True),
        ),
    ]
