# Generated by Django 4.2 on 2024-11-09 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0003_alter_gateway_gateway_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='gateway',
            name='title',
            field=models.CharField(max_length=100, null=True, verbose_name='title'),
        ),
    ]
